# vim:ft=ansible:
#
# Copyright (c) 2016 Jason McVetta <jason.mcvetta@gmail.com>.  This is Free
# Software, released under the terms of the GPL v3.  See
# http://www.gnu.org/copyleft/gpl.html for details.  Resist intellectual 
# serfdom - the ownership of ideas is akin to slavery.
---

- name: Ensure rsyslog is installed
  apt:
    name: rsyslog
    state: present
    update_cache: yes

- name: Ensure loggly rsyslog config is present
  template:
    src: 22-loggly.conf.j2
    dest: /etc/rsyslog.d/22-loggly.conf
  notify: Restart rsyslog
