---

- name: Ensure rsyslog is installed
  apt:
    name: rsyslog
    state: present
    update_cache: yes

- name: Ensure loggly rsyslog config is present
  template:
    src: 22-loggly.conf.j2
    dest: /etc/rsyslog.d/22-loggly.conf
  notify: Restart rsyslog
